"""
This type stub file was generated by pyright.
"""

import logging
from typing import override

TZ_IDENTIFIER = ...
TZ = ...
LOG_RECORD_KEYS = ...
class JSONLogFormatter(logging.Formatter):
    def __init__(self, include_keys: list[str] | None = ..., datefmt: str = ...) -> None:
        ...
    
    @override
    def format(self, record: logging.LogRecord) -> str:
        ...
    
    @override
    def formatTime(self, record: logging.LogRecord, datefmt: str | None = ...) -> str:
        ...
    


