"""
This type stub file was generated by pyright.
"""

import logging

class MaxLevelFilter(logging.Filter):
    def __init__(self, max_level: str) -> None:
        ...
    
    def filter(self, record: logging.LogRecord) -> bool:
        ...
    


