"""
This type stub file was generated by pyright.
"""

import logging
from typing import Any, Literal
from rich.logging import RichHandler

class MyRichHandler(RichHandler):
    def __init__(self, file: Literal["stdout", "stderr"] = ..., **kwargs: Any) -> None:
        ...
    
    def emit(self, record: logging.LogRecord) -> None:
        ...
    


