"""
This type stub file was generated by pyright.
"""

import argparse
from pathlib import Path

def build_parser() -> argparse.ArgumentParser:
    ...

def write_file(path: Path, data: str, mode: str = ..., encoding: str | None = ...) -> None:
    ...

def write_dotenv(path: Path) -> None:
    ...

def write_json(path: Path) -> None:
    ...

def run() -> None:
    ...

if __name__ == "__main__":
    logger = ...
